esa_s2 bands and png new name format
kappazeta/cm-vsm pull request #13
Opened 2021-03-18 11:24 UTC by toshaklg

How it looks like:
![image](https://user-images.githubusercontent.com/43007372/111618597-3ae4bc80-87ed-11eb-81e4-dcf1a1f9d71b.png)

2021-03-18 11:30 UTC, indrek-sunter commented on vsm/lib/raster/esa_s2.cpp
> +			ss_path_out_nc << ss_path_out.str() << path_in.stem().string().substr(0, path_in.stem().string().find_last_of("_")) << "_tile_" << xi << "_" << yi << ".nc";
Perhaps we could have a function which performs
`path_in.stem().string().substr(0, path_in.stem().string().find_last_of("_"))`

2021-03-18 11:32 UTC, indrek-sunter commented on vsm/lib/raster/esa_s2.cpp
> +			ss_path_out_png << ss_path_out.str() << path_in.stem().string() << "_"<< "tile_" << xi << "_" << yi << ".png";
I would prefer to have spaces around << operators.

2021-03-18 11:33 UTC, indrek-sunter commented on vsm/lib/raster/esa_s2.cpp
> +			ss_path_out_png << ss_path_out.str() << path_in.stem().string() << "_"<< "tile_" << xi << "_" << yi << ".png";
Same here, would prefer spaces around <<

2021-03-18 11:33 UTC, indrek-sunter commented on vsm/lib/raster/esa_s2.cpp
> +			ss_path_out_png << ss_path_out.str() << path_in.stem().string() << "_"<< "tile_" << xi << "_" << yi << ".png";
And here, would prefer spaces around <<

2021-03-18 11:33 UTC, indrek-sunter requested changes
Perhaps a few minor changes

2021-03-22 09:30 UTC, indrek-sunter requested changes
Also, perhaps we could also make the necessary changes in the rasterization and other converters?

2021-03-22 09:30 UTC, indrek-sunter commented on vsm/include/raster/esa_s2.hpp
> +		std::string index_date_band_extractor(const std::filesystem::path &path);
I think `extract_index_date_band` would be better.

2021-03-22 13:43 UTC, indrek-sunter commented on vsm/lib/raster/esa_s2.cpp
> +
Minor: Empty line :)

2021-03-23 07:30 UTC, toshaklg commented
The folder with segments.ai now looks like:
![segmentsai](https://user-images.githubusercontent.com/43007372/112109432-40118500-8bba-11eb-813d-55157dbe3b81.png)

2021-03-23 10:13 UTC, indrek-sunter approved these changes

2021-03-23 10:13 UTC, merged